# Generated by Django 3.0.4 on 2020-10-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('contact', models.CharField(max_length=15)),
                ('gmail', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
