# Generated by Django 3.0.4 on 2020-10-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodlivesapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table1',
        ),
    ]
