# Generated by Django 3.0.4 on 2020-10-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodlivesapp', '0004_auto_20201007_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='dob',
        ),
    ]
