# Generated by Django 3.0.4 on 2020-10-08 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodlivesapp', '0005_auto_20201008_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
